program: src/vec_train_mnk.py
method: bayes
metric:
  name: validation/vs_benchmark/score_rate
parameters:
  learning_rate:
    min: 0.00005
    max: 0.001
    distribution: log_uniform_values
  entropy_coef:
    distribution: log_uniform_values
    min: 1.0e-4 # 0.0001
    max: 1.0e-2 # 0.01
  batch_size:
    values: [64, 256, 1024]
  architecture_name:
    values: ["transformer_s"]