program: src/train_short.py
method: random
parameters:
  learning_rate:
    min: 1e-5
    max: 2e-3
    distribution: log_uniform_values
  entropy_coef:
    distribution: log_uniform_values
    min: 0.001
    max: 0.2
  architecture_name:
    values: ["transformer_b_s", "resnet_b_s", "cnn_b_s"]